
name: Build Expo Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  build:
    name: Build Expo APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Dependências
        run: npm install

      - name: Configurar Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Verificar Instalação Expo
        run: npx expo-doctor

      - name: Compilar App para Android (APK)
        run: npx eas build --platform android --profile preview --non-interactive --local
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload do APK Gerado
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./build/*.apk
