name: Build Expo Android App

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  build:
    name: Build Expo APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Dependências
        run: npm install

      - name: Configurar Expo
        run: npx expo install

      - name: Login no Expo
        run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      - name: Compilar App para Android (APK)
        run: npx eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload do APK Gerado
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: dist/*.apk
